.DEFAULT_GOAL := help
SHELL := /bin/bash
UV ?= uv
PY ?= $(UV) run
COMPOSE ?= docker compose

#: Where the shared gateway client lives when it is not installed from an index.
#:
#: ``bifrost-sdk`` is its own repository, and a Docker build cannot reach a sibling directory:
#: the build context is this repo, so an editable path of "../bifrost-sdk" resolves to nothing
#: inside the image and ``uv sync --frozen`` fails outright. Vendoring a copy *into* the
#: context is what makes the image buildable, and regenerating it from every target that needs
#: it is what stops that copy becoming a second source of truth. When the SDK is published to
#: an index this whole mechanism deletes itself: the dependency becomes an ordinary version.
BIFROST_SDK ?= ../bifrost-sdk
VENDOR := vendor/bifrost-sdk

.PHONY: vendor
vendor: ## Refresh the vendored copy of bifrost-sdk (generated; never edit it in place)
	@test -d "$(BIFROST_SDK)" || { \
	  echo "bifrost-sdk not found at $(BIFROST_SDK); set BIFROST_SDK=/path/to/bifrost-sdk" >&2; \
	  exit 1; }
	@# Removed first, not rsync --delete: with several sources --delete does not prune
	@# inside the transferred tree, so a renamed package left its old directory behind and
	@# the image would have shipped both.
	@rm -rf $(VENDOR)
	@mkdir -p $(VENDOR)
	@rsync -a --exclude .venv --exclude __pycache__ --exclude .git \
	  "$(BIFROST_SDK)/src" "$(BIFROST_SDK)/pyproject.toml" "$(BIFROST_SDK)/README.md" $(VENDOR)/
	@printf '%s\n' \
	  "Generated by \`make vendor\` from $(BIFROST_SDK). Edits here are overwritten." \
	  > $(VENDOR)/VENDORED.md

.PHONY: help setup models models-all dev-up dev-down migrate lint format typecheck unit integration contract-test e2e security-test \
        performance-test failure-test eval bench-retrieval bench-advanced bench-memory bench-embedding bench-storage \
        load-test bench-model-throughput bench-context-latency bench-locomo bench-locomo-prepare bench-locomo-source bench-rerank-offline bench-runtime-retrieval bench-budget bench-external bench-external-prepare gates gates-network validate verify verify-fresh verify-quick smoke openapi reindex examples clean

help: ## Show targets
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

setup: vendor ## Create .venv with uv and install all extras + dev tools
	$(UV) venv .venv --python 3.12
	$(UV) sync --all-extras --dev
	$(PY) pre-commit install || true

setup-min: vendor ## Minimal install (core + dev, no models/docling)
	$(UV) venv .venv --python 3.12
	$(UV) sync --dev

dev-up: vendor ## Start dev stack (postgres, qdrant, dragonfly, openfga, api, worker)
	$(COMPOSE) up -d --build

dev-down: ## Stop dev stack
	$(COMPOSE) down -v

models: ## Download the frozen model set (+ docling artifacts) into ./models (git-ignored)
	$(PY) python -m memory_service.tools.download_models

models-all: ## The frozen set plus every benchmark challenger listed in benchmark/challengers.txt
	$(PY) python -m memory_service.tools.download_models
	$(PY) python -m memory_service.tools.download_models --challengers benchmark/challengers.txt

migrate: ## Apply database migrations
	$(PY) alembic upgrade head
	$(PY) python -m memory_service.adapters.tasks.procrastinate_schema || true

lint: vendor ## Ruff lint + format check (format drift was never gated, so 13 files had drifted)
	$(PY) ruff check .
	$(PY) ruff format --check .

format: ## Ruff format + import sort
	$(PY) ruff format .
	$(PY) ruff check --fix .

typecheck: ## Pyright
	$(PY) pyright

unit: vendor ## Unit tests (no external services)
	$(PY) pytest tests/unit sdk/python/tests -m "not docker and not models" -q

integration: vendor ## Integration tests (needs Postgres/Redis; uses embedded fallbacks where possible)
	$(PY) pytest tests/integration -m "not docker and not models" -q

contract-test: vendor ## OpenAPI + provider contract tests
	$(PY) pytest tests/contract -q

e2e: vendor ## End-to-end API flows
	$(PY) pytest tests/e2e -m "not docker and not models" -q
	$(PY) pytest tests/agent -m "not docker and not models" -q

model-test: ## Local-model contract tests against real weights, inside the runtime image
	@# torch and onnxruntime publish no macOS x86_64 wheels, so on an Intel Mac the [models]
	@# extra cannot be installed at all and these tests can only run in the Linux image —
	@# which already carries the runtime. ./models is mounted read-only.
	docker run --rm --user root \
	  -v "$(CURDIR)":/app -v "$(CURDIR)/models":/models:ro \
	  -e PYTHONPATH=/app/src:/app -e VIRTUAL_ENV=/opt/venv \
	  --entrypoint sh memory-service-memory-api -c '\
	    uv pip install -q pytest pytest-asyncio anyio && cd /app && \
	    /opt/venv/bin/python -m pytest $(MODEL_TESTS) -q -p no:randomly -p no:cacheprovider'

MODEL_TESTS ?= tests/contract/test_nli_adapter.py tests/contract/test_model_adapters.py

security-test: ## Isolation / authorization gates (release blocking)
	$(PY) pytest tests/security -q

performance-test: ## Latency budgets (writes benchmark/results/performance.json)
	$(PY) python -m benchmark.performance

eval: ## Deterministic retrieval/memory evaluation gates
	$(PY) pytest tests/eval -m "not models" -q

bench-retrieval: ## Retrieval benchmark
	$(PY) python -m benchmark.retrieval

bench-advanced: ## Advanced retrieval strategies vs baseline (adoption verdicts)
	$(PY) python -m benchmark.advanced

bench-memory: ## Memory intelligence benchmark
	$(PY) python -m benchmark.memory
	$(PY) pytest tests/eval/test_tool_gate.py -q

#: One database per benchmark, not one shared between all of them.
#:
#: Every harness starts by TRUNCATEing its tables, so two benchmarks sharing a database means
#: whichever runs second destroys the first one's corpus. That is not hypothetical: a chained
#: LoCoMo run wiped a SciFact index that had cost forty minutes to build, and the only reason
#: it was noticed is that `--reuse-index` refuses to score an empty store. Separate databases
#: also make an index reusable across the arms of an ablation, which is the difference between
#: a second arm costing one minute and costing forty.
BENCH_DB_HOST ?= postgresql+psycopg://memory:memory@host.docker.internal:5432
BENCH_DB_DOCS ?= $(BENCH_DB_HOST)/memory_bench_docs
BENCH_DB_CONV ?= $(BENCH_DB_HOST)/memory_bench_conv
BENCH_DB_DEGEN ?= $(BENCH_DB_HOST)/memory_bench_degen
BENCH_DB_GOLDEN ?= $(BENCH_DB_HOST)/memory_bench_golden
BENCH_DB_PERF ?= $(BENCH_DB_HOST)/memory_bench_perf
#: Phase 7 (M2 + M4) owns its own databases, so an arm of this phase never competes with a
#: corpus another phase left behind and the source harness's dedicated-name rule is satisfied
#: by the default rather than by remembering to override it.
BENCH_DB_P7_CONV ?= $(BENCH_DB_HOST)/p7_locomo
BENCH_DB_P7_DOCS ?= $(BENCH_DB_HOST)/p7_retrieval
#: arm A1 changes the write path, so it gets its own corpus and its own database (spec 2.9)
BENCH_DB_P7_LLM ?= $(BENCH_DB_HOST)/p7_locomo_llm
BENCH_DB_P9_LME ?= $(BENCH_DB_HOST)/p9_longmemeval

#: The same server as BENCH_DB_HOST, reached from the *host* rather than from inside a
#: container: migrations run on the host with the project's own alembic, benchmarks run
#: inside the image and reach postgres through host.docker.internal.
BENCH_DB_HOST_LOCAL ?= postgresql+psycopg://memory:memory@localhost:5432
PG_CONTAINER ?= memory-service-postgres-1

#: Benchmarks run against the *real* Qdrant, not the in-process one.
#:
#: `BENCH_SEARCH=memory` puts qdrant-client in local mode, and local mode is an exact brute-force
#: scan with no HNSW index. That is fine for a fixture-sized corpus and quietly invalidates
#: anything larger: every de-duplication lookup during indexing scans the whole collection,
#: so ingest becomes O(n²) and queries O(n). Measured on BeIR/SciFact — the first 250
#: documents indexed in ~3 minutes, the second 250 took over ten, and a full 5,183-document
#: run never finished indexing before the harness moved on to querying, which scored
#: nDCG@10 = 0.012 against a published ~0.65 and read like a retrieval failure. It was the
#: backend, not the retrieval.
#: Tenant the document benchmark writes under. Overridable so an index built by one run
#: can be scored by another without paying to rebuild it.
BENCH_TENANT ?= bench_docs
#: torch intra-op threads for the concurrency benchmark; empty means torch's own default.
BENCH_THREADS ?=
BENCH_SEARCH ?= qdrant
#: The encoder is frozen (src/memory_service/config/constants.py); `make bench-embedding`
#: is where challengers are compared, never a flag on the product.
#: The ISOLATED Qdrant (16333/16334), never the shared dev store on 6333. A benchmark
#: ingests a corpus and deletes it again; the dev store on 6333 is serving a running API, so
#: pointing a harness at it both pollutes those reads and measures against the pollution.
#: The source harness refuses any other port; ``reset_store`` refuses any non-benchmark
#: database. This default is what makes the refusals unnecessary rather than routine.
BENCH_QDRANT_URL ?= http://host.docker.internal:16333
#: The gateway, reached from inside the benchmark container. It holds the provider key;
#: the service is only ever told a URL and a model name.
BIFROST_URL ?= http://host.docker.internal:8091/v1
# Flash-class only, on purpose: the judge and the answerer are classification-sized calls.
# Gemini 3.8 Flash is the gateway model that answered on 2026-09-28 (Anthropic had no credit,
# Gemini 2.5 Flash is retired, and DeepSeek is excluded by provenance - see
# src/memory_service/domain/provenance.py). Pace with --calls-per-minute; a judged LoCoMo
# arm is ~2,000 calls, so run the 20-question smoke first and read the cost it reports.
# The answerer and the judge are the same model here; separating them is Phase 4.
BENCH_LLM_MODEL ?= gemini/gemini-3.8-flash
# The gateway credential the judged runs spend through: the Bifrost virtual key that caps the
# accuracy budget (governance key "memory-accuracy-usd10", 10 USD/year, OpenRouter nano/mini
# and gemini-3.8-flash only). Export it from .env: `set -a; . ./.env; set +a`.
BIFROST_VIRTUAL_KEY ?=
BENCH_LIMIT ?=

#: Every containerised benchmark runs through this one block. It passes exactly what the
#: harness reads and nothing else: the database this benchmark owns, the Qdrant server, the
#: BENCH_* switches that benchmark/env.py (BenchEnv) turns into build_container overrides,
#: and the commit for provenance. The embedding is pinned to the frozen weights baked under
#: /models: BenchEnv's weights-follow default (the hash stand-in when ./models is missing)
#: is for a host checkout, never for the image. Retrieval depth, models and stand-ins are
#: NOT here - the seven copies of this block that used to carry ~25 -e lines each are where
#: the shipped service and the benchmarked service drifted apart (three tunings of one
#: retriever).
#:   $(1) database URL   $(2) extra -e flags   $(3) the command inside the image
define bench-run
	docker run --rm --user root \
	  -v "$(CURDIR)":/app -v "$(CURDIR)/models":/models:ro \
	  --add-host host.docker.internal:host-gateway \
	  -e PYTHONPATH=/app/src:/app -e VIRTUAL_ENV=/opt/venv \
	  -e PYTHONFAULTHANDLER=1 \
	  -e GIT_COMMIT=$(shell git rev-parse HEAD) \
	  -e MEMORY__DATABASE__URL="$(1)" \
	  -e BENCH_SEARCH=$(BENCH_SEARCH) -e BENCH_EMBEDDING=frozen \
	  -e MEMORY__SEARCH__QDRANT_URL=$(BENCH_QDRANT_URL) \
	  -e MEMORY__SEARCH__QDRANT_GRPC_PORT=$(BENCH_QDRANT_GRPC_PORT) \
	  -e BENCH_DENSE=$(BENCH_DENSE) \
	  $(2) \
	  --entrypoint sh $(BENCH_IMAGE) -c '$(BENCH_PRELUDE) $(3)'
endef

#: The runtime image the benchmarks run in (the repository is mounted over its /app).
BENCH_IMAGE ?= memory-service-memory-api

#: The image predates the temporal normaliser, so the one pure-Python dependency it lacks is
#: installed into the throwaway container the way `model-test` installs pytest; nothing is
#: rebuilt and nothing persists. Set BENCH_PRELUDE= when the image carries it.
BENCH_PRELUDE ?= uv pip install -q "dateparser>=1.2" &&
#: gRPC port beside BENCH_QDRANT_URL (the isolated store publishes 16333/16334)
BENCH_QDRANT_GRPC_PORT ?= 16334
#: ensemble (both dense spaces, the shipped runtime) | english (the single-encoder arm)
BENCH_DENSE ?= ensemble

#: The query-side arms of D6, passed through BENCH_EXTRA_ENV so one arm is one change:
#:
#:   step 2, fitted weights at half the candidate depth (the fit prints the JSON):
#:     BENCH_EXTRA_ENV='-e BENCH_DEPTH=halved -e BENCH_HYBRID_WEIGHTS={"bm25":2.0,...}'
#:   the actor/topic memory search, pinned off for a control arm now that it ships on:
#:     BENCH_EXTRA_ENV='-e BENCH_MEMORY_ENTITY_SEARCH=off'
#:
#: Unset, each leaves its constant alone: `hybrid_weights` stays None until the arm that
#: measured it clears its own gate. (The entity prefetch arm measured nothing: removed.)

#: The judged configuration: the gateway answers and grades, at the judged depth
#: (benchmark/env.py: PREFETCH_K/FUSED_K/FINAL_K/MEMORIES_MAX/TOKEN_BUDGET, and the judge's
#: MAX_TOKENS, TIMEOUT and retries off - a provider counts *wire* requests, so max_retries=2
#: sends three per logical call and a run paced at half the documented limit still exceeds
#: it). BENCH_LLM=on is the opt-in: without it a benchmark never reads the gateway variables.
#: The only use the bench tenant's policy allows is the judge (benchmark/env.py JUDGE_USES):
#: the former ambiguous-extraction/worthiness ingest uses were measured harmful (v2 -> v3:
#: 0.674 -> 0.661, p50 281 -> 572 ms) and were removed.
BENCH_LLM_ENV = -e BENCH_DEPTH=judged \
  -e BENCH_LLM=on \
  -e BIFROST_URL="$(BIFROST_URL)" \
  -e BIFROST_VIRTUAL_KEY="$(BIFROST_VIRTUAL_KEY)" \
  -e BENCH_LLM_MODEL="$(BENCH_LLM_MODEL)"

bench-db: ## Create and migrate the benchmark databases (idempotent, safe to re-run)
	@# Benchmarks used to assume `memory_bench` already existed, so on any machine that had
	@# not had it created by hand the first benchmark failed with a connection error that
	@# said nothing about the cause. Each benchmark owns one database; see BENCH_DB_* above.
	@for db in memory_bench_docs memory_bench_conv memory_bench_degen memory_bench_golden memory_bench_perf \
	          p7_locomo p7_retrieval p7_locomo_llm; do \
	  docker exec $(PG_CONTAINER) psql -U memory -d postgres -tAc \
	    "SELECT 1 FROM pg_database WHERE datname='$$db'" | grep -q 1 \
	    || docker exec $(PG_CONTAINER) createdb -U memory "$$db"; \
	  echo "migrating $$db"; \
	  MEMORY__DATABASE__URL="$(BENCH_DB_HOST_LOCAL)/$$db" $(PY) alembic upgrade head >/dev/null; \
	done
	@echo "benchmark databases ready"

bench-locomo-prepare: ## Download LoCoMo into benchmark/data (git-ignored)
	$(PY) python -m benchmark.prepare_locomo

bench-locomo: bench-db ## Conversational memory accuracy on LoCoMo, real models (inside the runtime image)
	@# The benchmark that matches what this service is: multi-session conversations, answers
	@# spread across sessions, annotated evidence turns, and 446 adversarial questions whose
	@# correct answer is to abstain.
	$(call bench-run,$(BENCH_DB_CONV),$(BENCH_EXTRA_ENV),/opt/venv/bin/python -m benchmark.locomo $(LOCOMO_ARGS))

#: Extra -e flags for a bench run, e.g. BENCH_EXTRA_ENV='-e BENCH_THREADED_INGEST=1'
#: to ingest inside a thread the way /v1/messages does.
BENCH_EXTRA_ENV ?=

LOCOMO_ARGS ?=
#: The corpus a LoCoMo arm runs against. Phase 7: BENCH_DB_P7_CONV for A0, BENCH_DB_P7_LLM
#: for A1 (its write path differs, so it cannot share A0's index).
LOCOMO_DB ?= $(BENCH_DB_CONV)

bench-external-prepare: ## Download BEIR SciFact into benchmark/data (git-ignored)
	$(PY) python -m benchmark.prepare_external

bench-locomo-judged: bench-db ## LoCoMo scored the way LoCoMo scores it: generate, then grade with a model
	@# Retries are off on purpose. A provider counts *wire* requests, so max_retries=2 sends
	@# three of them per logical call and a run paced at half the documented limit still
	@# exceeds it — measured against a 20-requests-per-minute free tier, which answered 17
	@# rate limits before the client gave up. With retries off, the pacer's rate is the
	@# actual request rate, and --calls-per-minute means what it says.
	@# The only configuration in which the adversarial category means anything. The gateway
	@# holds the provider key; this container is given a URL and a model name, never a secret.
	@# LOCOMO_DB selects the arm's corpus: Phase 7's A0 is BENCH_DB_P7_CONV and A1, which
	@# changes the write path, is BENCH_DB_P7_LLM. Only a dedicated database is accepted.
	$(call bench-run,$(LOCOMO_DB),$(BENCH_LLM_ENV) $(BENCH_EXTRA_ENV),/opt/venv/bin/python -m benchmark.locomo --judge $(LOCOMO_ARGS))

bench-locomo-source: bench-db ## LoCoMo source-ID coverage, no LLM, per-arm rank dumps (inside the runtime image)
	@# The ID-keyed source-recall harness (benchmark/native_source_retrieval.py): exact
	@# annotated source turns at depths 10/20/50/100, one tenant per conversation with
	@# --reuse-corpus, and every retriever's own ranking with --dump-arms for the offline
	@# weight fit. Refuses any database not named memory_hi_*/p7_*/p9_* and any Qdrant but the
	@# isolated one on 16333.
	$(call bench-run,$(BENCH_DB_P7_CONV),$(BENCH_EXTRA_ENV),/opt/venv/bin/python -m benchmark.native_source_retrieval --data benchmark/data/locomo10.json $(SOURCE_ARGS))

SOURCE_ARGS ?= --output benchmark/results/phase7/locomo_source.json --reuse-corpus --dump-arms

bench-rerank-offline: ## Does a cross-encoder rank better than the fused order? (over a finished dump)
	@# No retrieval, no training, no query-time cost: the bundle each question already returned
	@# is rescored by the cross-encoder and reordered, so the only thing that changes is the
	@# order. The corpus is read for the candidates' text and never written, so this does not
	@# depend on bench-db. The reranker weights are the ones baked under /models.
	$(call bench-run,$(BENCH_DB_P7_CONV),$(BENCH_EXTRA_ENV),/opt/venv/bin/python -m benchmark.rerank_offline $(RERANK_ARGS))

RERANK_ARGS ?= --dump benchmark/results/phase7/locomo_source_ensemble.json \
  --output benchmark/results/phase9/rerank_offline_ettin17m.json

bench-runtime-retrieval: bench-db ## SciFact and XQuAD through the runtime store path (named vectors, script-pruned prefetch)
	@# The M2 gates: SciFact >= 0.7557/0.8926 and XQuAD mean same-language R@10 >= 0.98,
	@# measured through what ships rather than an offline list fusion (benchmark/runtime_retrieval.py).
	$(call bench-run,$(BENCH_DB_P7_DOCS),-e BENCH_GRAPH_ENRICHMENT=disabled $(BENCH_EXTRA_ENV),/opt/venv/bin/python -m benchmark.runtime_retrieval $(RUNTIME_ARGS))

RUNTIME_ARGS ?= --suite scifact --output benchmark/results/phase7/runtime_scifact.json

bench-context-latency: bench-db ## /v1/context (with and without tools) and /v1/recall p50/p95, model off, real encoders
	@# The read path's latency gate (spec 4.10: p95 < 300 ms): a LoCoMo conversation recorded
	@# turn by turn, the golden documents and a tool catalog; every measured request misses
	@# the caches, and the stage split of every context is kept (benchmark/context_latency.py).
	$(call bench-run,$(BENCH_DB_PERF),-e BENCH_CACHE=dragonfly -e MEMORY__CACHE__URL=redis://host.docker.internal:6379/9 $(BENCH_EXTRA_ENV),/opt/venv/bin/python -m benchmark.context_latency $(CONTEXT_LATENCY_ARGS))

CONTEXT_LATENCY_ARGS ?= --label baseline

bench-budget: ## Read the accuracy key's usage (BENCH_BUDGET_KEY_ID); BUDGET_ARGS='guard --projected-usd 0.2' refuses an unaffordable arm
	$(PY) python -m benchmark.budget $(BUDGET_ARGS)

BUDGET_ARGS ?= read

bench-locomo-rescore: ## Re-grade an existing judged LoCoMo result under another ruler or judge (no retrieval)
	@# RESCORE_ARGS='benchmark/results/locomo_judged_v5.json --judge-ruler lenient'
	@# add --judge-model openai/gpt-4.1-mini to measure the judge's own contribution to a score
	$(call bench-run,$(BENCH_DB_CONV),$(BENCH_LLM_ENV),/opt/venv/bin/python -m benchmark.locomo_rescore $(RESCORE_ARGS))

RESCORE_ARGS ?=

bench-longmemeval: bench-db ## LongMemEval-S (cleaned), judged, real models (inside the runtime image)
	@# The other public conversational-memory benchmark the field quotes (Mem0 94.4,
	@# Zep 90.2). Same environment as bench-locomo-judged so the two are comparable
	@# with each other; the harness fetches the dataset from the HF hub on first use.
	$(call bench-run,$(BENCH_DB_CONV),$(BENCH_LLM_ENV),/opt/venv/bin/python -m benchmark.public --suite longmemeval --configs native $(LME_ARGS))

LME_ARGS ?=

bench-longmemeval-retrieval: bench-db ## LongMemEval-S evidence recall through the read path, no LLM (inside the runtime image)
	@# Turn- and session-level recall@10/20/50/100 of the context builder's memories, per
	@# question type (benchmark/longmemeval_retrieval.py). Every haystack is ingested from an
	@# empty store: --questions takes a stratified sample (seed 7) where all 470 do not fit.
	$(call bench-run,$(BENCH_DB_P9_LME),$(BENCH_EXTRA_ENV),/opt/venv/bin/python -m benchmark.longmemeval_retrieval --data benchmark/data/longmemeval/longmemeval_s_cleaned.json $(LMER_ARGS))

LMER_ARGS ?= --output benchmark/results/phase10/longmemeval_retrieval.json

bench-golden: bench-db ## Hierarchical-corpus retrieval with real models (sections, tables, footnotes)
	@# The instrument for the expansion flags. A flat corpus cannot measure them: SciFact
	@# abstracts are one chunk each, so parent/neighbour/definition expansion never fires and
	@# every ablation reads exactly zero. This golden set has section hierarchy and
	@# `required_groups`, which is the mechanism those flags serve.
	$(call bench-run,$(BENCH_DB_GOLDEN),-e BENCH_GRAPH_ENRICHMENT=disabled,/opt/venv/bin/python -m benchmark.retrieval $(GOLDEN_ARGS))

bench-concurrency: ## How much parallelism the model tier wants, and what it costs in RSS
	@# `service.worker_concurrency=4` and `models.threads=None` are unmeasured defaults: four
	@# jobs enter the same torch module while torch fans each op across every core. This
	@# measures throughput, peak RSS and — the part that matters — whether concurrent results
	@# still agree with sequential ones on a shared, unlocked module.
	$(call bench-run,$(BENCH_DB_DOCS),-e BENCH_SEARCH=memory -e BENCH_GRAPH_ENRICHMENT=disabled -e BENCH_THREADS="$(BENCH_THREADS)",/opt/venv/bin/python -m benchmark.concurrency $(CONCURRENCY_ARGS))

bench-degenerate: bench-db ## Behaviour on empty/garbage/hostile input, real models (inside the runtime image)
	@# The input the service actually receives, as opposed to the input it was designed for.
	@# Scores nothing; records what happened so a change in behaviour is visible.
	$(call bench-run,$(BENCH_DB_DEGEN),-e BENCH_GRAPH_ENRICHMENT=disabled,/opt/venv/bin/python -m benchmark.degenerate $(DEGENERATE_ARGS))

bench-external: bench-db ## Retrieval quality on an external corpus, with the real models (inside the runtime image)
	@# torch has no macOS x86_64 wheels, so the only place the real embedding model runs is the
	@# Linux image — the same reason `model-test` exists. Postgres is reached on the host.
	$(call bench-run,$(BENCH_DB_DOCS),-e BENCH_GRAPH_ENRICHMENT=disabled -e BENCH_TENANT="$(BENCH_TENANT)",/opt/venv/bin/python -m benchmark.external_retrieval $(BENCH_LIMIT))

bench-model-throughput: ## Per-model items/sec for capacity planning (run this ON the target VM)
	@# Sizing cannot be extrapolated from a developer laptop: transformer inference leans on
	@# AVX2/AVX-512/AMX, and a CPU without them is an order of magnitude slower. Run on the
	@# hardware you intend to deploy, then divide the target RPS by the measured rate.
	$(call bench-run,$(BENCH_DB_DOCS),,/opt/venv/bin/python -m benchmark.model_throughput --threads $(THREADS))

THREADS ?= 1 2 4 8

bench-embedding: ## Embedding runtime benchmark
	$(PY) python -m benchmark.embedding

bench-storage: ## Archive segment / storage benchmark
	$(PY) python -m benchmark.storage

BASE_URL ?= http://localhost:8080
API_KEY ?= dev-key

load-test: ## Locust load test (headless) -> benchmark/results/$(LOAD_OUT) (BASE_URL, API_KEY, LOAD_RPS, LOAD_ARM)
	@# LOAD_RPS is the offered rate: the locustfile paces each user at one request a second,
	@# so users == requests per second. The cold arm salts every query so the bundle cache
	@# misses. Run this from a quiet box - and, for a real number, from a different one.
	$(PY) python -m benchmark.load.run --base-url $(BASE_URL) --api-key $(API_KEY) \
	  -u $(LOAD_RPS) -r $(LOAD_RPS) -t $(LOAD_TIME) --arm $(LOAD_ARM) \
	  --sample $(LOAD_SAMPLE) --out $(LOAD_OUT)

LOAD_RPS ?= 10
LOAD_TIME ?= 300s
LOAD_ARM ?= cold
LOAD_SAMPLE ?= memory-service-memory-api-1
LOAD_OUT ?= load_test.json

gates-network: ## Network-hop gates against a deployed api + real workers (BASE_URL, API_KEY): durability_network, performance_network, load_test
	$(PY) python -m benchmark.deployed --base-url $(BASE_URL) --api-key $(API_KEY)
	$(PY) python -m benchmark.load.run --base-url $(BASE_URL) --api-key $(API_KEY) -u 20 -r 5 -t 60s

openapi: ## Export OpenAPI schema
	$(PY) python -m memory_service.tools.export_openapi docs/openapi.json

failure-test: ## Failure-injection scenarios (worker kill, cache flush, blob outage, index rebuild, authz outage)
	$(PY) pytest tests/failure -m failure -q

gates: ## Produce every release-gate artifact under benchmark/results/
	$(PY) pytest tests sdk/python/tests -m "not docker and not models" -q -p benchmark.pytest_results
	$(PY) python -m benchmark.security
	$(PY) python -m benchmark.failure_injection
	$(PY) python -m benchmark.durability
	$(PY) python -m benchmark.performance
	$(PY) python -m benchmark.retrieval
	$(PY) python -m benchmark.memory

examples: ## Run the SDK tour against a running server (uv run python examples/serve.py)
	$(PY) python examples/sdk_tour.py

reindex: ## Rebuild the search index from PostgreSQL (add --drop for a full rebuild)
	@# Needs the encoder, so it needs torch or onnxruntime in the *host* environment. Neither
	@# publishes a macOS x86_64 wheel, so on an Intel Mac this target cannot run and
	@# `reindex-image` is the one to use. It is left as the default because on Linux, where
	@# the wheels exist, running it in-process is faster and needs no image.
	$(PY) python -m memory_service.tools.reindex $(REINDEX_ARGS)

REINDEX_ARGS ?=
REINDEX_DB ?= $(BENCH_DB_HOST)/memory
REINDEX_QDRANT ?= $(BENCH_QDRANT_URL)

reindex-image: ## reindex inside the runtime image (the only way on a host without torch wheels)
	@# The same tool, given the models and a database, in the image that already carries the
	@# encoder. REINDEX_DB and REINDEX_QDRANT point it at a store; they default to the dev
	@# stack, and a benchmark database is named the same way the BENCH_DB_* variables are.
	docker run --rm --user root \
	  -v "$(CURDIR)":/app -v "$(CURDIR)/models":/models:ro \
	  --add-host host.docker.internal:host-gateway \
	  -e PYTHONPATH=/app/src:/app -e VIRTUAL_ENV=/opt/venv \
	  -e MEMORY__DATABASE__URL="$(REINDEX_DB)" \
	  -e MEMORY__SEARCH__QDRANT_URL="$(REINDEX_QDRANT)" \
	  --entrypoint sh memory-service-memory-api \
	  -c '/opt/venv/bin/python -m memory_service.tools.reindex $(REINDEX_ARGS)'

verify: ## The gate to pass before saying "it works": lint, fresh artifacts, live stack, smoke, both suites
	./scripts/verify.sh

verify-fresh: ## verify, but tears the stack down first INCLUDING VOLUMES and rebuilds it
	./scripts/verify.sh --fresh

verify-quick: ## verify without Docker: lint, fresh artifacts, unit + contract only
	./scripts/verify.sh --quick

smoke: ## One real turn through a running API (BASE_URL, API_KEY)
	BASE_URL=$(BASE_URL) API_KEY=$(API_KEY) $(PY) python scripts/smoke.py

validate: ## Full release gate: lint, types, every suite, gate artifacts, then the gate evaluator
	$(MAKE) lint
	$(MAKE) typecheck
	$(MAKE) gates
	$(PY) python -m benchmark.release_gate

clean:
	rm -rf .venv .pytest_cache .ruff_cache .mypy_cache dist build .blob
