.DEFAULT_GOAL := help
SHELL := /bin/bash
UV ?= uv
PY ?= $(UV) run
COMPOSE ?= docker compose

#: Where the shared gateway client lives when it is not installed from an index.
#:
#: ``bifrost-sdk`` is its own repository, and a Docker build cannot reach a sibling directory:
#: the build context is this repo, so an editable path of "../bifrost-sdk" resolves to nothing
#: inside the image and ``uv sync --frozen`` fails outright. Vendoring a copy *into* the
#: context is what makes the image buildable, and regenerating it from every target that needs
#: it is what stops that copy becoming a second source of truth. When the SDK is published to
#: an index this whole mechanism deletes itself: the dependency becomes an ordinary version.
BIFROST_SDK ?= ../bifrost-sdk
VENDOR := vendor/bifrost-sdk

.PHONY: vendor
vendor: ## Refresh the vendored copy of bifrost-sdk (generated; never edit it in place)
	@test -d "$(BIFROST_SDK)" || { \
	  echo "bifrost-sdk not found at $(BIFROST_SDK); set BIFROST_SDK=/path/to/bifrost-sdk" >&2; \
	  exit 1; }
	@# Removed first, not rsync --delete: with several sources --delete does not prune
	@# inside the transferred tree, so a renamed package left its old directory behind and
	@# the image would have shipped both.
	@rm -rf $(VENDOR)
	@mkdir -p $(VENDOR)
	@rsync -a --exclude .venv --exclude __pycache__ --exclude .git \
	  "$(BIFROST_SDK)/src" "$(BIFROST_SDK)/pyproject.toml" "$(BIFROST_SDK)/README.md" $(VENDOR)/
	@printf '%s\n' \
	  "Generated by \`make vendor\` from $(BIFROST_SDK). Edits here are overwritten." \
	  > $(VENDOR)/VENDORED.md

.PHONY: help setup models models-all dev-up dev-down migrate lint format typecheck unit integration contract-test e2e security-test \
        performance-test failure-test eval bench-retrieval bench-advanced bench-memory bench-embedding bench-reranker bench-storage \
        load-test bench-model-throughput bench-locomo bench-locomo-prepare bench-external bench-external-prepare gates gates-network validate verify verify-fresh verify-quick smoke openapi reindex examples clean

help: ## Show targets
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

setup: vendor ## Create .venv with uv and install all extras + dev tools
	$(UV) venv .venv --python 3.12
	$(UV) sync --all-extras --dev
	$(PY) pre-commit install || true

setup-min: vendor ## Minimal install (core + dev, no models/docling/cognee)
	$(UV) venv .venv --python 3.12
	$(UV) sync --dev

dev-up: vendor ## Start dev stack (postgres, qdrant, dragonfly, openfga, api, worker)
	$(COMPOSE) up -d --build

dev-down: ## Stop dev stack
	$(COMPOSE) down -v

models: ## Download the default model weights into ./models (git-ignored)
	$(PY) python -m memory_service.tools.download_models

models-all: ## Download the defaults plus every benchmark challenger
	$(PY) python -m memory_service.tools.download_models --all

migrate: ## Apply database migrations
	$(PY) alembic upgrade head
	$(PY) python -m memory_service.adapters.tasks.procrastinate_schema || true

lint: vendor ## Ruff lint + format check (format drift was never gated, so 13 files had drifted)
	$(PY) ruff check .
	$(PY) ruff format --check .

format: ## Ruff format + import sort
	$(PY) ruff format .
	$(PY) ruff check --fix .

typecheck: ## Pyright
	$(PY) pyright

unit: vendor ## Unit tests (no external services)
	$(PY) pytest tests/unit sdk/python/tests -m "not docker and not models" -q

integration: vendor ## Integration tests (needs Postgres/Redis; uses embedded fallbacks where possible)
	$(PY) pytest tests/integration -m "not docker and not models" -q

contract-test: vendor ## OpenAPI + provider contract tests
	$(PY) pytest tests/contract -q

e2e: vendor ## End-to-end API flows
	$(PY) pytest tests/e2e -m "not docker and not models" -q

model-test: ## Local-model contract tests against real weights, inside the runtime image
	@# torch and onnxruntime publish no macOS x86_64 wheels, so on an Intel Mac the [models]
	@# extra cannot be installed at all and these tests can only run in the Linux image —
	@# which already carries the runtime. ./models is mounted read-only.
	docker run --rm --user root \
	  -v "$(CURDIR)":/app -v "$(CURDIR)/models":/models:ro \
	  -e PYTHONPATH=/app/src:/app -e VIRTUAL_ENV=/opt/venv \
	  --entrypoint sh memory-service-memory-api -c '\
	    uv pip install -q pytest pytest-asyncio anyio && cd /app && \
	    /opt/venv/bin/python -m pytest $(MODEL_TESTS) -q -p no:randomly -p no:cacheprovider'

MODEL_TESTS ?= tests/contract/test_advanced_adapters.py tests/contract/test_nli_adapter.py tests/contract/test_model_adapters.py

security-test: ## Isolation / authorization gates (release blocking)
	$(PY) pytest tests/security -q

performance-test: ## Latency budgets (writes benchmark/results/performance.json)
	$(PY) python -m benchmark.performance

eval: ## Deterministic retrieval/memory evaluation gates
	$(PY) pytest tests/eval -m "not models" -q

bench-retrieval: ## Retrieval benchmark
	$(PY) python -m benchmark.retrieval

bench-advanced: ## Advanced retrieval strategies vs baseline (adoption verdicts)
	$(PY) python -m benchmark.advanced

bench-memory: ## Memory intelligence benchmark
	$(PY) python -m benchmark.memory
	$(PY) pytest tests/eval/test_tool_gate.py -q

#: One database per benchmark, not one shared between all of them.
#:
#: Every harness starts by TRUNCATEing its tables, so two benchmarks sharing a database means
#: whichever runs second destroys the first one's corpus. That is not hypothetical: a chained
#: LoCoMo run wiped a SciFact index that had cost forty minutes to build, and the only reason
#: it was noticed is that `--reuse-index` refuses to score an empty store. Separate databases
#: also make an index reusable across the arms of an ablation, which is the difference between
#: a second arm costing one minute and costing forty.
BENCH_DB_HOST ?= postgresql+psycopg://memory:memory@host.docker.internal:5432
BENCH_DB_DOCS ?= $(BENCH_DB_HOST)/memory_bench_docs
BENCH_DB_CONV ?= $(BENCH_DB_HOST)/memory_bench_conv
BENCH_DB_DEGEN ?= $(BENCH_DB_HOST)/memory_bench_degen
BENCH_DB_GOLDEN ?= $(BENCH_DB_HOST)/memory_bench_golden

#: The same server as BENCH_DB_HOST, reached from the *host* rather than from inside a
#: container: migrations run on the host with the project's own alembic, benchmarks run
#: inside the image and reach postgres through host.docker.internal.
BENCH_DB_HOST_LOCAL ?= postgresql+psycopg://memory:memory@localhost:5432
PG_CONTAINER ?= memory-service-postgres-1

#: Benchmarks run against the *real* Qdrant, not the in-process one.
#:
#: `BENCH_SEARCH=memory` puts qdrant-client in local mode, and local mode is an exact brute-force
#: scan with no HNSW index. That is fine for a fixture-sized corpus and quietly invalidates
#: anything larger: every de-duplication lookup during indexing scans the whole collection,
#: so ingest becomes O(n²) and queries O(n). Measured on BeIR/SciFact — the first 250
#: documents indexed in ~3 minutes, the second 250 took over ten, and a full 5,183-document
#: run never finished indexing before the harness moved on to querying, which scored
#: nDCG@10 = 0.012 against a published ~0.65 and read like a retrieval failure. It was the
#: backend, not the retrieval.
#: Tenant the document benchmark writes under. Overridable so an index built by one run
#: can be scored by another without paying to rebuild it.
BENCH_TENANT ?= bench_docs
#: torch intra-op threads for the concurrency benchmark; empty means torch's own default.
BENCH_THREADS ?=
BENCH_SEARCH ?= qdrant
#: The encoder is frozen (src/memory_service/config/constants.py); `make bench-embedding`
#: is where challengers are compared, never a flag on the product.
BENCH_QDRANT_URL ?= http://host.docker.internal:6333
#: The gateway, reached from inside the benchmark container. It holds the provider key;
#: the service is only ever told a URL and a model name.
BIFROST_URL ?= http://host.docker.internal:8091/v1
# DeepSeek V4.1-Flash. Flash only, on purpose: the judge and the answerer are
# classification-sized calls, and the cheap tier is $0.30/$1.20 per 1M tokens
# ($0.15/$0.60 off-peak) against deepseek-v4-pro at $0.435/$0.87. It also limits by
# concurrency rather than a daily quota, which is what broke the last judged run:
# 17 HTTP 429s from a free Gemini key, then 62 calls the circuit breaker refused.
# The answerer and the judge are the same model here; separating them is Phase 4.
BENCH_LLM_MODEL ?= deepseek/deepseek-flash
BENCH_LIMIT ?=

#: Every containerised benchmark runs through this one block. It passes exactly what the
#: harness reads and nothing else: the database this benchmark owns, the Qdrant server, the
#: BENCH_* switches that benchmark/env.py (BenchEnv) turns into build_container overrides,
#: and the commit for provenance. Retrieval depth, models and stand-ins are NOT here - the
#: seven copies of this block that used to carry ~25 -e lines each are where the shipped
#: service and the benchmarked service drifted apart (three tunings of one retriever).
#:   $(1) database URL   $(2) extra -e flags   $(3) the command inside the image
define bench-run
	docker run --rm --user root \
	  -v "$(CURDIR)":/app -v "$(CURDIR)/models":/models:ro \
	  --add-host host.docker.internal:host-gateway \
	  -e PYTHONPATH=/app/src:/app -e VIRTUAL_ENV=/opt/venv \
	  -e PYTHONFAULTHANDLER=1 \
	  -e GIT_COMMIT=$(shell git rev-parse HEAD) \
	  -e MEMORY__DATABASE__URL="$(1)" \
	  -e BENCH_SEARCH=$(BENCH_SEARCH) -e MEMORY__SEARCH__QDRANT_URL=$(BENCH_QDRANT_URL) \
	  $(2) \
	  --entrypoint sh memory-service-memory-api -c '$(3)'
endef

#: The judged configuration: the gateway answers and grades, at the judged depth
#: (benchmark/env.py: PREFETCH_K/FUSED_K/FINAL_K/MEMORIES_MAX/TOKEN_BUDGET, MAX_TOKENS,
#: TIMEOUT, retries off - a provider counts *wire* requests, so max_retries=2 sends three per
#: logical call and a run paced at half the documented limit still exceeds it). The only
#: LLM use is the judge: ambiguous_worthiness / ambiguous_extraction at ingest were measured
#: harmful (v2 -> v3: 0.674 -> 0.661, p50 281 -> 572 ms) and are off.
BENCH_LLM_ENV = -e BENCH_DEPTH=judged \
  -e MEMORY__MODELS__LLM__ENABLED=true \
  -e MEMORY__MODELS__LLM__BASE_URL="$(BIFROST_URL)" \
  -e MEMORY__MODELS__LLM__MODEL="$(BENCH_LLM_MODEL)" \
  -e MEMORY__MODELS__LLM__FAST_MODEL="$(BENCH_LLM_MODEL)" \
  -e MEMORY__MODELS__LLM__USES='["grounding_judge"]' \
  -e MEMORY__MODELS__LLM__FAST_USES='["grounding_judge"]'

bench-db: ## Create and migrate the benchmark databases (idempotent, safe to re-run)
	@# Benchmarks used to assume `memory_bench` already existed, so on any machine that had
	@# not had it created by hand the first benchmark failed with a connection error that
	@# said nothing about the cause. Each benchmark owns one database; see BENCH_DB_* above.
	@for db in memory_bench_docs memory_bench_conv memory_bench_degen memory_bench_golden; do \
	  docker exec $(PG_CONTAINER) psql -U memory -d postgres -tAc \
	    "SELECT 1 FROM pg_database WHERE datname='$$db'" | grep -q 1 \
	    || docker exec $(PG_CONTAINER) createdb -U memory "$$db"; \
	  echo "migrating $$db"; \
	  MEMORY__DATABASE__URL="$(BENCH_DB_HOST_LOCAL)/$$db" $(PY) alembic upgrade head >/dev/null; \
	done
	@echo "benchmark databases ready"

bench-locomo-prepare: ## Download LoCoMo into benchmark/data (git-ignored)
	$(PY) python -m benchmark.prepare_locomo

bench-locomo: bench-db ## Conversational memory accuracy on LoCoMo, real models (inside the runtime image)
	@# The benchmark that matches what this service is: multi-session conversations, answers
	@# spread across sessions, annotated evidence turns, and 446 adversarial questions whose
	@# correct answer is to abstain.
	$(call bench-run,$(BENCH_DB_CONV),,/opt/venv/bin/python -m benchmark.locomo $(LOCOMO_ARGS))

LOCOMO_ARGS ?=

bench-external-prepare: ## Download BEIR SciFact into benchmark/data (git-ignored)
	$(PY) python -m benchmark.prepare_external

bench-locomo-judged: bench-db ## LoCoMo scored the way LoCoMo scores it: generate, then grade with a model
	@# Retries are off on purpose. A provider counts *wire* requests, so max_retries=2 sends
	@# three of them per logical call and a run paced at half the documented limit still
	@# exceeds it — measured against a 20-requests-per-minute free tier, which answered 17
	@# rate limits before the client gave up. With retries off, the pacer's rate is the
	@# actual request rate, and --calls-per-minute means what it says.
	@# The only configuration in which the adversarial category means anything. The gateway
	@# holds the provider key; this container is given a URL and a model name, never a secret.
	$(call bench-run,$(BENCH_DB_CONV),$(BENCH_LLM_ENV),/opt/venv/bin/python -m benchmark.locomo --judge $(LOCOMO_ARGS))

bench-locomo-rescore: ## Re-grade an existing judged LoCoMo result under another ruler (no retrieval)
	@# RESCORE_ARGS='benchmark/results/locomo_judged_v2.json --judge-ruler lenient'
	$(call bench-run,$(BENCH_DB_CONV),$(BENCH_LLM_ENV),/opt/venv/bin/python -m benchmark.locomo_rescore $(RESCORE_ARGS))

RESCORE_ARGS ?=

bench-longmemeval: bench-db ## LongMemEval-S (cleaned), judged, real models (inside the runtime image)
	@# The other public conversational-memory benchmark the field quotes (Mem0 94.4,
	@# Zep 90.2). Same environment as bench-locomo-judged so the two are comparable
	@# with each other; the harness fetches the dataset from the HF hub on first use.
	$(call bench-run,$(BENCH_DB_CONV),$(BENCH_LLM_ENV),/opt/venv/bin/python -m benchmark.public --suite longmemeval --configs native $(LME_ARGS))

LME_ARGS ?=

bench-golden: bench-db ## Hierarchical-corpus retrieval with real models (sections, tables, footnotes)
	@# The instrument for the expansion flags. A flat corpus cannot measure them: SciFact
	@# abstracts are one chunk each, so parent/neighbour/definition expansion never fires and
	@# every ablation reads exactly zero. This golden set has section hierarchy and
	@# `required_groups`, which is the mechanism those flags serve.
	$(call bench-run,$(BENCH_DB_GOLDEN),-e BENCH_GRAPH_ENRICHMENT=disabled,/opt/venv/bin/python -m benchmark.retrieval $(GOLDEN_ARGS))

bench-concurrency: ## How much parallelism the model tier wants, and what it costs in RSS
	@# `service.worker_concurrency=4` and `models.threads=None` are unmeasured defaults: four
	@# jobs enter the same torch module while torch fans each op across every core. This
	@# measures throughput, peak RSS and — the part that matters — whether concurrent results
	@# still agree with sequential ones on a shared, unlocked module.
	$(call bench-run,$(BENCH_DB_DOCS),-e BENCH_SEARCH=memory -e BENCH_GRAPH_ENRICHMENT=disabled -e MEMORY__MODELS__EMBEDDING__THREADS="$(BENCH_THREADS)",/opt/venv/bin/python -m benchmark.concurrency $(CONCURRENCY_ARGS))

bench-degenerate: bench-db ## Behaviour on empty/garbage/hostile input, real models (inside the runtime image)
	@# The input the service actually receives, as opposed to the input it was designed for.
	@# Scores nothing; records what happened so a change in behaviour is visible.
	$(call bench-run,$(BENCH_DB_DEGEN),-e BENCH_GRAPH_ENRICHMENT=disabled,/opt/venv/bin/python -m benchmark.degenerate $(DEGENERATE_ARGS))

bench-external: bench-db ## Retrieval quality on an external corpus, with the real models (inside the runtime image)
	@# torch has no macOS x86_64 wheels, so the only place the real embedding model runs is the
	@# Linux image — the same reason `model-test` exists. Postgres is reached on the host.
	$(call bench-run,$(BENCH_DB_DOCS),-e BENCH_GRAPH_ENRICHMENT=disabled -e BENCH_TENANT="$(BENCH_TENANT)",/opt/venv/bin/python -m benchmark.external_retrieval $(BENCH_LIMIT))

bench-model-throughput: ## Per-model items/sec for capacity planning (run this ON the target VM)
	@# Sizing cannot be extrapolated from a developer laptop: transformer inference leans on
	@# AVX2/AVX-512/AMX, and a CPU without them is an order of magnitude slower. Run on the
	@# hardware you intend to deploy, then divide the target RPS by the measured rate.
	$(call bench-run,$(BENCH_DB_DOCS),,/opt/venv/bin/python -m benchmark.model_throughput --threads $(THREADS))

THREADS ?= 1 2 4 8

bench-embedding: ## Embedding runtime benchmark
	$(PY) python -m benchmark.embedding

bench-reranker: ## Reranker benchmark
	$(PY) python -m benchmark.reranker

bench-storage: ## Archive segment / storage benchmark
	$(PY) python -m benchmark.storage

BASE_URL ?= http://localhost:8080
API_KEY ?= dev-key

load-test: ## Locust load test (headless) -> benchmark/results/load_test.json (BASE_URL, API_KEY)
	$(PY) python -m benchmark.load.run --base-url $(BASE_URL) --api-key $(API_KEY) -u 20 -r 5 -t 60s

gates-network: ## Network-hop gates against a deployed api + real workers (BASE_URL, API_KEY): durability_network, performance_network, load_test
	$(PY) python -m benchmark.deployed --base-url $(BASE_URL) --api-key $(API_KEY)
	$(PY) python -m benchmark.load.run --base-url $(BASE_URL) --api-key $(API_KEY) -u 20 -r 5 -t 60s

openapi: ## Export OpenAPI schema
	$(PY) python -m memory_service.tools.export_openapi docs/openapi.json

failure-test: ## Failure-injection scenarios (worker kill, cache flush, blob outage, index rebuild, authz outage)
	$(PY) pytest tests/failure -m failure -q

gates: ## Produce every release-gate artifact under benchmark/results/
	$(PY) pytest tests sdk/python/tests -m "not docker and not models" -q -p benchmark.pytest_results
	$(PY) python -m benchmark.security
	$(PY) python -m benchmark.failure_injection
	$(PY) python -m benchmark.durability
	$(PY) python -m benchmark.performance
	$(PY) python -m benchmark.retrieval
	$(PY) python -m benchmark.memory

examples: ## Run the SDK tour against a running server (./examples/run_server.sh)
	$(PY) python examples/sdk_tour.py

reindex: ## Rebuild the search index from PostgreSQL (add --drop for a full rebuild)
	$(PY) python -m memory_service.tools.reindex

verify: ## The gate to pass before saying "it works": lint, fresh artifacts, live stack, smoke, both suites
	./scripts/verify.sh

verify-fresh: ## verify, but tears the stack down first INCLUDING VOLUMES and rebuilds it
	./scripts/verify.sh --fresh

verify-quick: ## verify without Docker: lint, fresh artifacts, unit + contract only
	./scripts/verify.sh --quick

smoke: ## One real turn through a running API (BASE_URL, API_KEY)
	BASE_URL=$(BASE_URL) API_KEY=$(API_KEY) $(PY) python scripts/smoke.py

validate: ## Full release gate: lint, types, every suite, gate artifacts, then the gate evaluator
	$(MAKE) lint
	$(MAKE) typecheck
	$(MAKE) gates
	$(PY) python -m benchmark.release_gate

clean:
	rm -rf .venv .pytest_cache .ruff_cache .mypy_cache dist build .blob
