"""Framework-neutral building blocks shared by the framework adapters."""

from universal_memory.integrations.core import (
    SCOPE_FIELDS,
    AgentRun,
    Entry,
    EntryKind,
    EvidenceStatus,
    MemoryHooks,
    Message,
    Observation,
    Role,
    RunRecord,
    as_observations,
    bundle_entries,
    evidence_metadata,
    idempotency_key,
    item_entry,
    items_entries,
    message_text,
    normalize_role,
    render_bundle,
    render_entries,
    run_sync,
    safe_id,
    scope_fields,
)

__all__ = [
    "SCOPE_FIELDS",
    "AgentRun",
    "Entry",
    "EntryKind",
    "EvidenceStatus",
    "MemoryHooks",
    "Message",
    "Observation",
    "Role",
    "RunRecord",
    "as_observations",
    "bundle_entries",
    "evidence_metadata",
    "idempotency_key",
    "item_entry",
    "items_entries",
    "message_text",
    "normalize_role",
    "render_bundle",
    "render_entries",
    "run_sync",
    "safe_id",
    "scope_fields",
]
