"""m1_canonical_persistence

Revision ID: ff2aaf3d03f0
Revises: 
Create Date: 2026-09-14 22:52:38.820304+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('agent_run_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('thread_id', sa.String(length=200), nullable=True),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('turn_id', sa.String(length=200), nullable=True),
    sa.Column('work_id', sa.String(length=200), nullable=True),
    sa.Column('task_id', sa.String(length=200), nullable=True),
    sa.Column('agent_id', sa.String(length=200), nullable=False),
    sa.Column('agent_group_id', sa.String(length=200), nullable=True),
    sa.Column('parent_agent_run_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='RUNNING', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.String(length=200), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('agent_run_id')
    )
    op.create_index('ix_agent_runs_parent', 'agent_runs', ['parent_agent_run_id'], unique=False)
    op.create_index('ix_agent_runs_turn', 'agent_runs', ['tenant_id', 'turn_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'key')
    )
    op.create_index('ix_idempotency_expires', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('job_outbox',
    sa.Column('outbox_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=True),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('queue', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('idempotency_key', sa.String(length=300), nullable=True),
    sa.Column('lock', sa.String(length=300), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('schedule_in_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_id', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dead', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('outbox_id')
    )
    op.create_index('ix_job_outbox_pending', 'job_outbox', ['created_at'], unique=False, postgresql_where=sa.text('dispatched_at IS NULL AND dead = false'))
    op.create_index('uq_job_outbox_idempotency', 'job_outbox', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('observations',
    sa.Column('observation_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('thread_id', sa.String(length=200), nullable=True),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('turn_id', sa.String(length=200), nullable=True),
    sa.Column('work_id', sa.String(length=200), nullable=True),
    sa.Column('task_id', sa.String(length=200), nullable=True),
    sa.Column('agent_id', sa.String(length=200), nullable=True),
    sa.Column('agent_group_id', sa.String(length=200), nullable=True),
    sa.Column('agent_run_id', sa.String(length=200), nullable=True),
    sa.Column('parent_agent_run_id', sa.String(length=200), nullable=True),
    sa.Column('principal_id', sa.String(length=300), nullable=False),
    sa.Column('trace_id', sa.String(length=200), nullable=True),
    sa.Column('message_id', sa.String(length=200), nullable=True),
    sa.Column('document_id', sa.String(length=200), nullable=True),
    sa.Column('tool_run_id', sa.String(length=200), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=400), nullable=True),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_index('ix_observations_pending', 'observations', ['created_at'], unique=False, postgresql_where=sa.text('processed_at IS NULL'))
    op.create_index('ix_observations_tenant_created', 'observations', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_observations_thread', 'observations', ['tenant_id', 'thread_id', 'created_at'], unique=False)
    op.create_table('revisions',
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.String(length=200), nullable=False),
    sa.Column('value', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'kind', 'object_id')
    )
    op.create_table('threads',
    sa.Column('thread_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('workspace_id', sa.String(length=200), nullable=True),
    sa.Column('owner_user_id', sa.String(length=200), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_thread_id', sa.String(length=400), nullable=True),
    sa.Column('system_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index('ix_threads_source', 'threads', ['tenant_id', 'source_system', 'source_thread_id'], unique=False)
    op.create_index('ix_threads_tenant_owner_updated', 'threads', ['tenant_id', 'owner_user_id', 'updated_at'], unique=False)
    op.create_index('ix_threads_tenant_workspace', 'threads', ['tenant_id', 'workspace_id'], unique=False)
    op.create_table('turn_run_links',
    sa.Column('turn_id', sa.String(length=200), nullable=False),
    sa.Column('agent_run_id', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('turn_id', 'agent_run_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('thread_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('client', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_sessions_thread', 'sessions', ['thread_id', 'started_at'], unique=False)
    op.create_table('turns',
    sa.Column('turn_id', sa.String(length=200), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('thread_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('turn_id'),
    sa.UniqueConstraint('thread_id', 'sequence', name='uq_turns_thread_sequence')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=200), nullable=False),
    sa.Column('thread_id', sa.String(length=200), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('turn_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('author_principal', sa.String(length=300), nullable=False),
    sa.Column('agent_run_id', sa.String(length=200), nullable=True),
    sa.Column('parent_message_id', sa.String(length=200), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_message_id', sa.String(length=400), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archive_status', sa.String(length=20), server_default='STAGED', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_segment_id', sa.String(length=200), nullable=True),
    sa.Column('system_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('thread_id', 'sequence', name='uq_messages_thread_sequence')
    )
    op.create_index('ix_messages_source', 'messages', ['tenant_id', 'source_system', 'source_message_id'], unique=False)
    op.create_index('ix_messages_staged', 'messages', ['tenant_id', 'created_at'], unique=False, postgresql_where=sa.text("archive_status = 'STAGED'"))
    op.create_index('ix_messages_tenant_thread_seq', 'messages', ['tenant_id', 'thread_id', 'sequence'], unique=False)
    op.create_index('ix_messages_turn', 'messages', ['turn_id'], unique=False)
    op.create_table('message_attachments',
    sa.Column('attachment_id', sa.String(length=200), nullable=False),
    sa.Column('message_id', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.String(length=200), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index('ix_message_attachments_message', 'message_attachments', ['message_id'], unique=False)
    op.create_table('message_versions',
    sa.Column('message_version_id', sa.String(length=200), nullable=False),
    sa.Column('message_id', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_version_id'),
    sa.UniqueConstraint('message_id', 'version', name='uq_message_versions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_versions')
    op.drop_index('ix_message_attachments_message', table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index('ix_messages_turn', table_name='messages')
    op.drop_index('ix_messages_tenant_thread_seq', table_name='messages')
    op.drop_index('ix_messages_staged', table_name='messages', postgresql_where=sa.text("archive_status = 'STAGED'"))
    op.drop_index('ix_messages_source', table_name='messages')
    op.drop_table('messages')
    op.drop_table('turns')
    op.drop_index('ix_sessions_thread', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('turn_run_links')
    op.drop_index('ix_threads_tenant_workspace', table_name='threads')
    op.drop_index('ix_threads_tenant_owner_updated', table_name='threads')
    op.drop_index('ix_threads_source', table_name='threads')
    op.drop_table('threads')
    op.drop_table('revisions')
    op.drop_index('ix_observations_thread', table_name='observations')
    op.drop_index('ix_observations_tenant_created', table_name='observations')
    op.drop_index('ix_observations_pending', table_name='observations', postgresql_where=sa.text('processed_at IS NULL'))
    op.drop_table('observations')
    op.drop_index('uq_job_outbox_idempotency', table_name='job_outbox', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_job_outbox_pending', table_name='job_outbox', postgresql_where=sa.text('dispatched_at IS NULL AND dead = false'))
    op.drop_table('job_outbox')
    op.drop_index('ix_idempotency_expires', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_agent_runs_turn', table_name='agent_runs')
    op.drop_index('ix_agent_runs_parent', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
