"""m4_archive_segments

Revision ID: f33c08c24673
Revises: 0001
Create Date: 2026-09-14 23:17:43.217684+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_segments',
    sa.Column('segment_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('thread_id', sa.String(length=200), nullable=True),
    sa.Column('document_id', sa.String(length=200), nullable=True),
    sa.Column('bucket', sa.String(length=200), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('generation', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('raw_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('first_sequence', sa.Integer(), nullable=True),
    sa.Column('last_sequence', sa.Integer(), nullable=True),
    sa.Column('first_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_index('ix_archive_segments_status', 'archive_segments', ['status', 'created_at'], unique=False)
    op.create_index('ix_archive_segments_thread', 'archive_segments', ['tenant_id', 'thread_id', 'first_sequence'], unique=False)
    op.create_index('uq_archive_segments_key', 'archive_segments', ['bucket', 'key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_archive_segments_key', table_name='archive_segments')
    op.drop_index('ix_archive_segments_thread', table_name='archive_segments')
    op.drop_index('ix_archive_segments_status', table_name='archive_segments')
    op.drop_table('archive_segments')
    # ### end Alembic commands ###
