"""m5_documents

Revision ID: 9109694eacfd
Revises: 0002
Create Date: 2026-09-14 23:29:33.717399+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('workspace_id', sa.String(length=200), nullable=True),
    sa.Column('owner_user_id', sa.String(length=200), nullable=True),
    sa.Column('thread_id', sa.String(length=200), nullable=True),
    sa.Column('message_id', sa.String(length=200), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('current_version_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=400), nullable=True),
    sa.Column('archive_status', sa.String(length=20), server_default='STAGED', nullable=False),
    sa.Column('archive_segment_id', sa.String(length=200), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visibility_keys', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('system_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index('ix_documents_status', 'documents', ['status', 'created_at'], unique=False)
    op.create_index('ix_documents_tenant_checksum', 'documents', ['tenant_id', 'checksum'], unique=False)
    op.create_index('ix_documents_tenant_thread', 'documents', ['tenant_id', 'thread_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.String(length=200), nullable=False),
    sa.Column('node_id', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.String(length=200), nullable=False),
    sa.Column('document_version_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('contextual_text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('index_fingerprint', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_chunks_tenant_document', 'chunks', ['tenant_id', 'document_id'], unique=False)
    op.create_index('ix_chunks_text_hash', 'chunks', ['tenant_id', 'text_hash'], unique=False)
    op.create_index('ix_chunks_version', 'chunks', ['document_version_id', 'node_id', 'ordinal'], unique=False)
    op.create_table('context_edges',
    sa.Column('edge_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.String(length=300), nullable=False),
    sa.Column('target_id', sa.String(length=300), nullable=False),
    sa.Column('edge', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index('ix_context_edges_document', 'context_edges', ['document_id'], unique=False)
    op.create_index('ix_context_edges_source', 'context_edges', ['source_id', 'edge'], unique=False)
    op.create_index('ix_context_edges_target', 'context_edges', ['target_id', 'edge'], unique=False)
    op.create_table('document_nodes',
    sa.Column('node_id', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.String(length=200), nullable=False),
    sa.Column('document_version_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('representation', sa.String(length=30), nullable=False),
    sa.Column('parent_id', sa.String(length=200), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('system_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index('ix_document_nodes_parent', 'document_nodes', ['parent_id'], unique=False)
    op.create_index('ix_document_nodes_version', 'document_nodes', ['document_version_id', 'depth', 'ordinal'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_version_id', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parser', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_version_id')
    )
    op.create_index('ix_document_versions_document', 'document_versions', ['document_id', 'version'], unique=False)
    op.create_table('file_staging',
    sa.Column('document_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_staging')
    op.drop_index('ix_document_versions_document', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_document_nodes_version', table_name='document_nodes')
    op.drop_index('ix_document_nodes_parent', table_name='document_nodes')
    op.drop_table('document_nodes')
    op.drop_index('ix_context_edges_target', table_name='context_edges')
    op.drop_index('ix_context_edges_source', table_name='context_edges')
    op.drop_index('ix_context_edges_document', table_name='context_edges')
    op.drop_table('context_edges')
    op.drop_index('ix_chunks_version', table_name='chunks')
    op.drop_index('ix_chunks_text_hash', table_name='chunks')
    op.drop_index('ix_chunks_tenant_document', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_documents_tenant_thread', table_name='documents')
    op.drop_index('ix_documents_tenant_checksum', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
