"""m7_memories

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-15 00:10:38.523227+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('memory_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('scope_level', sa.String(length=20), nullable=False),
    sa.Column('scope_key', sa.String(length=600), nullable=False),
    sa.Column('workspace_id', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('group_id', sa.String(length=200), nullable=True),
    sa.Column('thread_id', sa.String(length=200), nullable=True),
    sa.Column('work_id', sa.String(length=200), nullable=True),
    sa.Column('agent_id', sa.String(length=200), nullable=True),
    sa.Column('agent_group_id', sa.String(length=200), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('visibility_keys', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('owner_principal', sa.String(length=300), nullable=False),
    sa.Column('lifetime', sa.String(length=20), nullable=False),
    sa.Column('memory_type', sa.String(length=30), nullable=False),
    sa.Column('custom_type', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('predicate', sa.String(length=200), nullable=True),
    sa.Column('object', sa.Text(), nullable=True),
    sa.Column('temporal_status', sa.String(length=20), server_default='CURRENT', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_by', sa.String(length=200), nullable=True),
    sa.Column('supersedes', sa.String(length=200), nullable=True),
    sa.Column('contradicts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('importance', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('reinforcement_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('provider', sa.String(length=40), server_default='native', nullable=False),
    sa.Column('system_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('index_fingerprint', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index('ix_memories_expiring', 'memories', ['expires_at'], unique=False, postgresql_where=sa.text('expires_at IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('ix_memories_tenant_hash', 'memories', ['tenant_id', 'normalized_hash'], unique=False)
    op.create_index('ix_memories_tenant_scope', 'memories', ['tenant_id', 'scope_key', 'temporal_status'], unique=False)
    op.create_index('ix_memories_tenant_subject', 'memories', ['tenant_id', 'subject', 'predicate'], unique=False)
    op.create_index('ix_memories_tenant_thread', 'memories', ['tenant_id', 'thread_id'], unique=False)
    op.create_index('ix_memories_tenant_user', 'memories', ['tenant_id', 'user_id', 'created_at'], unique=False)
    op.create_index('ix_memories_unindexed', 'memories', ['tenant_id', 'created_at'], unique=False, postgresql_where=sa.text('indexed_at IS NULL AND deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memories_unindexed', table_name='memories', postgresql_where=sa.text('indexed_at IS NULL AND deleted_at IS NULL'))
    op.drop_index('ix_memories_tenant_user', table_name='memories')
    op.drop_index('ix_memories_tenant_thread', table_name='memories')
    op.drop_index('ix_memories_tenant_subject', table_name='memories')
    op.drop_index('ix_memories_tenant_scope', table_name='memories')
    op.drop_index('ix_memories_tenant_hash', table_name='memories')
    op.drop_index('ix_memories_expiring', table_name='memories', postgresql_where=sa.text('expires_at IS NOT NULL AND deleted_at IS NULL'))
    op.drop_table('memories')
    # ### end Alembic commands ###
