"""m8_graph

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-15 00:55:34.404239+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_entities',
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('scope_key', sa.String(length=600), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('visibility_keys', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('mention_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('tenant_id', 'scope_key', 'canonical_name', name='uq_graph_entity')
    )
    op.create_index('ix_graph_entities_keys', 'graph_entities', ['visibility_keys'], unique=False, postgresql_using='gin')
    op.create_index('ix_graph_entities_tenant_name', 'graph_entities', ['tenant_id', 'canonical_name'], unique=False)
    op.create_table('graph_relations',
    sa.Column('relation_id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('scope_key', sa.String(length=600), nullable=False),
    sa.Column('subject_id', sa.String(length=200), nullable=False),
    sa.Column('predicate', sa.String(length=120), nullable=False),
    sa.Column('object_id', sa.String(length=200), nullable=False),
    sa.Column('visibility_keys', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='CURRENT', nullable=False),
    sa.Column('superseded_by', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('memory_id', sa.String(length=200), nullable=True),
    sa.Column('document_id', sa.String(length=200), nullable=True),
    sa.Column('fact_text', sa.Text(), server_default='', nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_index('ix_graph_relations_document', 'graph_relations', ['tenant_id', 'document_id'], unique=False)
    op.create_index('ix_graph_relations_keys', 'graph_relations', ['visibility_keys'], unique=False, postgresql_using='gin')
    op.create_index('ix_graph_relations_memory', 'graph_relations', ['tenant_id', 'memory_id'], unique=False)
    op.create_index('ix_graph_relations_object', 'graph_relations', ['tenant_id', 'object_id', 'status'], unique=False)
    op.create_index('ix_graph_relations_slot', 'graph_relations', ['tenant_id', 'subject_id', 'predicate', 'status'], unique=False)
    op.create_index('ix_graph_relations_subject', 'graph_relations', ['tenant_id', 'subject_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_graph_relations_subject', table_name='graph_relations')
    op.drop_index('ix_graph_relations_slot', table_name='graph_relations')
    op.drop_index('ix_graph_relations_object', table_name='graph_relations')
    op.drop_index('ix_graph_relations_memory', table_name='graph_relations')
    op.drop_index('ix_graph_relations_keys', table_name='graph_relations', postgresql_using='gin')
    op.drop_index('ix_graph_relations_document', table_name='graph_relations')
    op.drop_table('graph_relations')
    op.drop_index('ix_graph_entities_tenant_name', table_name='graph_entities')
    op.drop_index('ix_graph_entities_keys', table_name='graph_entities', postgresql_using='gin')
    op.drop_table('graph_entities')
    # ### end Alembic commands ###
