"""Ports: protocols the application depends on. Adapters implement them."""

from memory_service.ports.authorization import (
    AccessCheck,
    AuthorizationProvider,
    AuthorizedScope,
    RelationTuple,
)
from memory_service.ports.blob import BlobChecksumMismatch, BlobNotFound, BlobRef, BlobStore
from memory_service.ports.cache import CacheProvider, CacheUnavailable
from memory_service.ports.intelligence import (
    ConsolidationOutcome,
    DocumentParser,
    Entity,
    GraphEnrichmentProvider,
    GraphNeighborhood,
    GraphStore,
    MemoryCandidate,
    MemoryIntelligenceProvider,
    ParsedDocument,
    Relation,
)
from memory_service.ports.models import (
    EmbeddingProvider,
    LLMCompletion,
    LLMMessage,
    LLMProvider,
    NLIProvider,
    NLIScore,
    ProviderInfo,
    Reranker,
    RerankResult,
    SparseEncoder,
)
from memory_service.ports.search import (
    CollectionSpec,
    SearchFilter,
    SearchHit,
    SearchRecord,
    SearchStore,
    SparseVector,
)
from memory_service.ports.tasks import (
    QUEUE_PRIORITY,
    JobInfo,
    JobSpec,
    Queue,
    TaskHandler,
    TaskQueue,
)

__all__ = [
    "QUEUE_PRIORITY",
    "AccessCheck",
    "AuthorizationProvider",
    "AuthorizedScope",
    "BlobChecksumMismatch",
    "BlobNotFound",
    "BlobRef",
    "BlobStore",
    "CacheProvider",
    "CacheUnavailable",
    "CollectionSpec",
    "ConsolidationOutcome",
    "DocumentParser",
    "EmbeddingProvider",
    "Entity",
    "GraphEnrichmentProvider",
    "GraphNeighborhood",
    "GraphStore",
    "JobInfo",
    "JobSpec",
    "LLMCompletion",
    "LLMMessage",
    "LLMProvider",
    "MemoryCandidate",
    "MemoryIntelligenceProvider",
    "NLIProvider",
    "NLIScore",
    "ParsedDocument",
    "ProviderInfo",
    "Queue",
    "Relation",
    "RelationTuple",
    "RerankResult",
    "Reranker",
    "SearchFilter",
    "SearchHit",
    "SearchRecord",
    "SearchStore",
    "SparseEncoder",
    "SparseVector",
    "TaskHandler",
    "TaskQueue",
]
