"""The vendored bifrost-sdk must match its source.

``vendor/bifrost-sdk`` is generated by ``make vendor`` and git-ignored, and the installed
package resolves to it — so a fix made in the real bifrost-sdk repository does not reach
this service until someone regenerates it. Every Makefile test target already depends on
``vendor``; running ``pytest`` directly, which is what most people do, does not.

That silence is the problem. It happened: the 429 handling was fixed upstream, the vendored
copy still carried ``response.text[:500]``, and the whole suite passed against the stale
code — including the tests that exist to cover rate limiting. The failure mode of a stale
vendor is a green run, which is why this is a test and not a comment.

Skipped, not failed, when the source is not on disk: a CI job that checks out only this
repository has nothing to compare against, and the image build regenerates the copy anyway.
"""

from __future__ import annotations

import filecmp
import os
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
VENDORED = REPO / "vendor" / "bifrost-sdk" / "src" / "bifrost_sdk"
SOURCE = Path(os.environ.get("BIFROST_SDK", REPO.parent / "bifrost-sdk")) / "src" / "bifrost_sdk"


def _python_files(root: Path) -> dict[str, Path]:
    return {
        str(path.relative_to(root)): path
        for path in sorted(root.rglob("*.py"))
        if "__pycache__" not in path.parts
    }


@pytest.mark.skipif(not SOURCE.is_dir(), reason=f"bifrost-sdk source not at {SOURCE}")
def test_the_vendored_copy_matches_its_source() -> None:
    assert VENDORED.is_dir(), (
        f"{VENDORED} is missing — run `make vendor`. The installed bifrost_sdk resolves here."
    )

    source = _python_files(SOURCE)
    vendored = _python_files(VENDORED)

    assert set(vendored) == set(source), (
        "the vendored copy has a different set of modules than the source "
        f"(only in vendor: {sorted(set(vendored) - set(source))}; "
        f"only in source: {sorted(set(source) - set(vendored))}) — run `make vendor`"
    )

    stale = [
        name
        for name, path in source.items()
        if not filecmp.cmp(path, vendored[name], shallow=False)
    ]
    assert not stale, (
        f"the vendored bifrost-sdk is stale: {sorted(stale)} differ from {SOURCE}. "
        f"Run `make vendor`. Until you do, the suite tests code that is not what ships."
    )


@pytest.mark.skipif(not SOURCE.is_dir(), reason=f"bifrost-sdk source not at {SOURCE}")
def test_the_installed_package_is_the_vendored_one() -> None:
    """If this ever stops being true, the test above is guarding the wrong directory."""
    import bifrost_sdk

    installed = Path(bifrost_sdk.__file__).resolve().parent
    assert installed == VENDORED.resolve(), (
        f"bifrost_sdk imports from {installed}, not the vendored copy at {VENDORED}"
    )
